<Project>
  <!-- Persist compile patch counter after each successful build. -->
  <Target
    Name="_PersistAndroidVersion"
    AfterTargets="Build"
    Condition="'$(DesignTimeBuild)' != 'true'">
    <WriteLinesToFile File="$(VersionStampFile)" Lines="$(_CurrentStamp)" Overwrite="true" />
    <WriteLinesToFile File="$(VersionPatchFile)" Lines="$(VersionPatch)" Overwrite="true" />
  </Target>
</Project>
